f11robo_bridge_node:
  ros__parameters:
    f11robo_bridge:
      topic_name:
        cmd_vel: "/cmd_vel"
      frame_id:
        odom: "odom"
        base_link: "base_link"
        imu_link: "imu_link"
      serial:
        port: "/dev/F11Robo"
        baudrate: 115200
      broadcast_period: 0.001
      odometry:
        use_imu: true
      tf_output: true
      rpy_inversion: [true, true, true]
      debug_output: true
      max:
        vel: 0.1 #[m/s]
        angular: 1.5 #[rad/s]
